### ISSUE TITLE
First iteration

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#16]
## User story

Implementation, interpretation and documentation of a first model

## Acceptance Criterion

* The exploration backs the model
* The results are interpreted
* The notebooks are annotated

## Tasks

* [x] Create the deliverables
* [x] Explore the dataset
* [x] Create a first simple model
* [x] Interpret and document this model
