### ISSUE TITLE
Second iteration

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#18]
## User story

Implementation, interpretation and documentation of a second version of the exploration and training.

## Acceptance Criterion

* The exploration backs the model
* The notebooks are annotated

## Tasks

* [x] Engineer new features
* [x] Train a simple baseline
* [x] Test multiple models
