### ISSUE TITLE
First iteration

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#24]
## User story

Make a first client segmentation as well as some visualisations.

## Acceptance Criterion

* Use PCA and t-SNE
* Use RFM, K-Means and DBSCAN
* Visualise the number of orders
* Inspect correlations

## Tasks

* [x] Implement PCA and t-SNE
* [x] Visualise reduction
* [x] Explore clustering
* [x] Interpret clusters
* [x] Simple (cat/num) plots
* [x] Orders across space and time
