### ISSUE TITLE
Baseline Engine

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#27]
## User story

Create a first baseline recommendation engine with its API.

## Acceptance Criterion

* The data extraction and cleaning are automated
* The API is available
* The code is documented

## Tasks

* [x] Extraction to create a dataset
* [x] Cleaning and brief exploration
* [x] Simple baseline model
* [x] Rest API on Azure
