### ISSUE TITLE
End of Project 5

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#30]
## User story

Completion of Project 5.

## Acceptance Criterion

* The notebooks are documented
* A git history is available for the API development
* Some functions are externalised in the package

## Tasks

* [x]  Finish the EDA
* [x] Complete the classification using other processing and models
* [x] Measure classification accuracy
* [x] Complete simple clustering
* [x] Compare clustering and classification
