### ISSUE TITLE
Presentation project 5

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#31]
## User story

Make a presentation of a good version of the project 5.

## Acceptance Criterion

* The advancement supports the presentation
* All the project specs are validated

## Tasks

* [x] Make schema to illustrate the EDA
* [x] Measure the performance of the classification
* [x] Propose first approaches for clustering
* [x] Create new versions of the API
