### ISSUE TITLE
Automated deployment for Project 5

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#32]
## User story

The API developed for Project 5 should be deployable using GitHub actions.

## Acceptance Criterion

* The pipeline makes use of environments
* No action is needed in Azure

## Tasks

* [x] CI: build-docker-image
* [x] CI: test-docker-image
* [x] CD: deploy-to-azure
