### ISSUE TITLE
Descriptive statistics

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#7]
## User story

First-step analysis by computing descriptive statistics.

## Acceptance Criterion

* Univariate analysis results presented
* Bivariate analysis results presented
  * Correlation matrix analysed

## Tasks

- [x] Conduct univariate analysis for numerical features
- [x] Conduct univariate analysis for categorical features
- [x] Conduct bivariate analysis for numerical and categorical features
- [x] Analyse the correlation matrix
