### ISSUE TITLE
Multivariate statistics

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/ML-Engineer#8]
## User story

Deeper statistical analysis empowered by multivariate methods like PCA and ANOVA.

## Acceptance Criterion

* PCA conducted
* Analysis of variance conducted
  * Statistical tests (p-value)

## Tasks
- [x] Conduct and present a PCA
- [x] Plot some correlation results
- [x] Conduct ANOVA on relevant features
- [x] Rely on statistical tests
